### ISSUE TITLE
Module can't generate ModuleGen file on specific case.

### ISSUE THREAD

**Issue by aerain** [InsertKoinIO/koin-annotations#14]
**Describe the bug**
When I declare same named two Module class in different packages,
koin-ksp-compiler failed to task.

**To Reproduce**
1. declare two Module class in different packages with same name.

`foo/DatabaseConfig.kt`
```kt
package foo

@Module
class DatabaseConfig {

    @Single
    @Named("mysql")
    fun mysql(): String = "this is mysql"
}
```

`bar/DatabaseConfig.kt`
```kt
package bar

@Module
class DatabaseConfig {
    @Single
    @Named("mariadb")
    fun mariadb(): String = "this is mariadb"
}
```
2. build
3. kspKotlin task failed.
```
[ksp] kotlin.io.FileAlreadyExistsException: [location]
        at com.google.devtools.ksp.processing.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:75)
	at com.google.devtools.ksp.processing.CodeGenerator$DefaultImpls.createNewFile$default(CodeGenerator.kt:59)
	at org.koin.compiler.generator.KoinGeneratorKt.getFile(KoinGenerator.kt:103)
	at org.koin.compiler.generator.KoinGeneratorKt.getFile$default(KoinGenerator.kt:103)
	at org.koin.compiler.generator.KoinGenerator.generateModule(KoinGenerator.kt:68)
	at org.koin.compiler.generator.KoinGenerator.generateModules(KoinGenerator.kt:49)
        ...
```

**Expected behavior**
Generate Two Module files successfully.

**Koin project used and used version (please complete the following information):**
koin-core: 3.2.0-beta-1
koin-annotations: 1.0.0-beta-2

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by arnaudgiuliani** [comment]
To follow with #15
