### ISSUE TITLE
Android Quickstart app crash

### ISSUE THREAD

**Issue by AKJAW** [InsertKoinIO/koin-annotations#26]
**Describe the bug**
I'm having trouble running the quickstart android app on the Android emulator (tested API 29 and 30). When installing the app through Android Studio, it crashes on start up, the same goes when opening the application from the menu.

**To Reproduce**
1. Pull the repository at [latest main branch](https://github.com/InsertKoinIO/koin-annotations/commit/d6725c41e3df25278f0604a55dc0f9e9edf6f143)
2. Install the Android application
3. The app crashes

Here's the logcat error message:
```
2022-05-18 18:57:42.473 552-919/system_process I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.sample.koin/org.koin.sample.view.presenter.MySimpleActivity bnds=[841,578][1043,892]} from uid 10138
2022-05-18 18:57:42.473 552-919/system_process W/ActivityTaskManager: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.sample.koin/org.koin.sample.view.presenter.MySimpleActivity bnds=[841,578][1043,892] } from ProcessRecord{3f9afee 1051:com.google.android.apps.nexuslauncher/u0a138} (pid=1051, uid=10138) not exported from uid 10154
2022-05-18 18:57:42.478 1051-1051/com.google.android.apps.nexuslauncher E/BaseDraggingActivity: Unable to launch. tag=AppInfo(id=-1 type=APP container=all_apps targetComponent=ComponentInfo{org.sample.koin/org.koin.sample.view.presenter.MySimpleActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Koin Sample App componentName=ComponentInfo{org.sample.koin/org.koin.sample.view.presenter.MySimpleActivity}) intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.sample.koin/org.koin.sample.view.presenter.MySimpleActivity bnds=[841,578][1043,892] }
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.sample.koin/org.koin.sample.view.presenter.MySimpleActivity bnds=[841,578][1043,892] } from ProcessRecord{3f9afee 1051:com.google.android.apps.nexuslauncher/u0a138} (pid=1051, uid=10138) not exported from uid 10154
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3696)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
        at android.app.Activity.startActivityForResult(Activity.java:5320)
        at com.android.launcher3.Launcher.startActivityForResult(SourceFile:2)
        at com.android.launcher3.BaseQuickstepLauncher.startActivityForResult(SourceFile:6)
        at android.app.Activity.startActivity(Activity.java:5660)
        at com.android.launcher3.BaseDraggingActivity.startActivitySafely(SourceFile:15)
        at com.android.launcher3.Launcher.startActivitySafely(SourceFile:7)
        at com.android.launcher3.uioverrides.QuickstepLauncher.startActivitySafely(SourceFile:3)
        at com.android.launcher3.touch.ItemClickHandler.startAppShortcutOrInfoActivity(SourceFile:15)
        at c.a.a.Y0.e.onClick(SourceFile:20)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1032)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:999)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:669)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1100)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1072)
```

The error can be avoided if the app is launched through App Info:
![Screenshot 2022-05-19 at 16 10 34](https://user-images.githubusercontent.com/26874608/169314193-50e7a47c-f790-4c4d-9042-caa6dab1fe42.png)

**Expected behavior**
The app doesn't crash

**Comment by arnaudgiuliani** [comment]
Thanks 👌

**Comment by arnaudgiuliani** [comment]
fixed, thanks
